# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
# Kakao
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'  # 카카오 로그인
pod 'KakaoSDKUser'  # 사용자 관리

# Google
pod 'GoogleSignIn' # 구글 로그인

target 'Morize (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Morize (iOS)

end

target 'Morize (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Morize (macOS)

end
